# Generated by Django 4.0.3 on 2022-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
